del /q /f Windows\System32\DriverStore\FileRepository\acpi.inf_amd64_neutral_aed2e7a487803437\acpi.PNF
del /q /f Windows\System32\DriverStore\FileRepository\battery.inf_amd64_neutral_0ff3dd8f4047f37b\battery.PNF
del /q /f Windows\System32\DriverStore\FileRepository\cdrom.inf_amd64_neutral_0b3d0d1942ab684b\cdrom.PNF
del /q /f Windows\System32\DriverStore\FileRepository\cpu.inf_amd64_neutral_32c143ab27a6b24f\cpu.PNF
del /q /f Windows\System32\DriverStore\FileRepository\hal.inf_amd64_neutral_a768502c7cb64799\hal.PNF
del /q /f Windows\System32\DriverStore\FileRepository\hidserv.inf_amd64_neutral_76a23552f0bfbb8d\hidserv.PNF
del /q /f Windows\System32\DriverStore\FileRepository\iastorv.inf_amd64_neutral_668286aa35d55928\iastorv.PNF
del /q /f Windows\System32\DriverStore\FileRepository\input.inf_amd64_neutral_8693053514b10ee9\input.PNF
del /q /f Windows\System32\DriverStore\FileRepository\ipmidrv.inf_amd64_neutral_1cb648411f252d13\ipmidrv.PNF
del /q /f Windows\System32\DriverStore\FileRepository\keyboard.inf_amd64_neutral_0684fdc43059f486\keyboard.PNF
del /q /f Windows\System32\DriverStore\FileRepository\machine.inf_amd64_neutral_a2f120466549d68b\machine.PNF
del /q /f Windows\System32\DriverStore\FileRepository\mshdc.inf_amd64_neutral_aad30bdeec04ea5e\mshdc.PNF
del /q /f Windows\System32\DriverStore\FileRepository\msmouse.inf_amd64_neutral_be54ff5547c95b94\msmouse.PNF
del /q /f Windows\System32\DriverStore\FileRepository\msports.inf_amd64_neutral_81fd97f70b912976\msports.PNF
del /q /f Windows\System32\DriverStore\FileRepository\mtconfig.inf_amd64_neutral_91a6025a8a8fc9e2\mtconfig.PNF
del /q /f Windows\System32\DriverStore\FileRepository\qd3x64.inf_amd64_neutral_e8903726d63a3f07\qd3x64.PNF
del /q /f Windows\System32\DriverStore\FileRepository\tpm.inf_amd64_neutral_d9aaed445a1b06ba\tpm.PNF
del /q /f Windows\System32\DriverStore\FileRepository\umbus.inf_amd64_neutral_2d4257afa2e35253\umbus.PNF
del /q /f Windows\System32\DriverStore\FileRepository\umpass.inf_amd64_neutral_e70ff1e33e2d446b\umpass.PNF
del /q /f Windows\System32\DriverStore\FileRepository\unknown.inf_amd64_neutral_62dd581b814cb8ea\unknown.PNF
del /q /f Windows\System32\DriverStore\FileRepository\usb.inf_amd64_neutral_269d7150439b3372\usb.PNF
del /q /f Windows\System32\DriverStore\FileRepository\usbport.inf_amd64_neutral_f935002f367d5bb0\usbport.PNF
del /q /f Windows\System32\DriverStore\FileRepository\usbstor.inf_amd64_neutral_0725c2806a159a9d\usbstor.PNF
del /q /f Windows\System32\DriverStore\FileRepository\vhdmp.inf_amd64_neutral_c3910bbf4fbccf97\vhdmp.PNF
del /q /f Windows\System32\DriverStore\FileRepository\volsnap.inf_amd64_neutral_78a0c392a927c59d\volsnap.PNF
del /q /f Windows\System32\DriverStore\FileRepository\wd.inf_amd64_neutral_39d179b4b05eca38\wd.PNF
del /q /f Windows\System32\DriverStore\FileRepository\wstorvsc.inf_amd64_neutral_d7bf942e99bb1d41\wstorvsc.PNF

rd /s /q Windows\System32\0407
rd /s /q "Program Files"
rd /s /q ProgramData
rd /s /q sources\recovery
rd /s /q sources\inf

rd /s /q Windows\Branding
rd /s /q Windows\Help
rd /s /q Windows\L2Schemas
rd /s /q Windows\LiveKernelReports
rd /s /q Windows\Logs
rd /s /q Windows\Microsoft.NET
rd /s /q Windows\PolicyDefinitions
rd /s /q Windows\resources
rd /s /q Windows\schemas
rd /s /q Windows\security
rd /s /q Windows\SysWOW64
rd /s /q Windows\Temp
rd /s /q Windows\tracing
rd /s /q Windows\Vss
rd /s /q Windows\wpeprofiles
del /q /f Windows\hh.exe
del /q /f Windows\fveupdate.exe
del /q /f Windows\de-DE\fveupdate.exe.mui
del /q /f Windows\de-DE\hh.exe.mui
del /q /f Windows\Fonts\*.ttf
del /q /f Windows\Fonts\8514fix.fon
del /q /f Windows\Fonts\8514fixe.fon
del /q /f Windows\Fonts\8514fixg.fon
del /q /f Windows\Fonts\8514fixr.fon
del /q /f Windows\Fonts\8514fixt.fon
del /q /f Windows\Fonts\8514oem.fon
del /q /f Windows\Fonts\8514oeme.fon
del /q /f Windows\Fonts\8514oemg.fon
del /q /f Windows\Fonts\8514oemr.fon
del /q /f Windows\Fonts\8514oemt.fon
del /q /f Windows\Fonts\8514sys.fon
del /q /f Windows\Fonts\8514syse.fon
del /q /f Windows\Fonts\8514sysg.fon
del /q /f Windows\Fonts\8514sysr.fon
del /q /f Windows\Fonts\8514syst.fon
del /q /f Windows\Fonts\85775.fon
del /q /f Windows\Fonts\85855.fon
del /q /f Windows\Fonts\85f1255.fon
del /q /f Windows\Fonts\85f1256.fon
del /q /f Windows\Fonts\85f1257.fon
del /q /f Windows\Fonts\85f874.fon
del /q /f Windows\Fonts\85s1255.fon
del /q /f Windows\Fonts\85s1256.fon
del /q /f Windows\Fonts\85s1257.fon
del /q /f Windows\Fonts\85s874.fon
del /q /f Windows\Fonts\app775.fon
del /q /f Windows\Fonts\app850.fon
del /q /f Windows\Fonts\app852.fon
del /q /f Windows\Fonts\app855.fon
del /q /f Windows\Fonts\app857.fon
del /q /f Windows\Fonts\app866.fon
del /q /f Windows\Fonts\app932.fon
del /q /f Windows\Fonts\app936.fon
del /q /f Windows\Fonts\app949.fon
del /q /f Windows\Fonts\app950.fon
del /q /f Windows\Fonts\c8514fix.fon
del /q /f Windows\Fonts\c8514oem.fon
del /q /f Windows\Fonts\c8514sys.fon
del /q /f Windows\Fonts\cga40737.fon
del /q /f Windows\Fonts\cga40850.fon
del /q /f Windows\Fonts\cga40852.fon
del /q /f Windows\Fonts\cga40857.fon
del /q /f Windows\Fonts\cga40866.fon
del /q /f Windows\Fonts\cga40869.fon
del /q /f Windows\Fonts\cga40woa.fon
del /q /f Windows\Fonts\cga80737.fon
del /q /f Windows\Fonts\cga80850.fon
del /q /f Windows\Fonts\cga80852.fon
del /q /f Windows\Fonts\cga80857.fon
del /q /f Windows\Fonts\cga80866.fon
del /q /f Windows\Fonts\cga80869.fon
del /q /f Windows\Fonts\cga80woa.fon
del /q /f Windows\Fonts\cvgafix.fon
del /q /f Windows\Fonts\cvgasys.fon
del /q /f Windows\Fonts\dos737.fon
del /q /f Windows\Fonts\dos869.fon
del /q /f Windows\Fonts\dosapp.fon
del /q /f Windows\Fonts\ega40737.fon
del /q /f Windows\Fonts\ega40850.fon
del /q /f Windows\Fonts\ega40852.fon
del /q /f Windows\Fonts\ega40857.fon
del /q /f Windows\Fonts\ega40866.fon
del /q /f Windows\Fonts\ega40869.fon
del /q /f Windows\Fonts\ega40woa.fon
del /q /f Windows\Fonts\ega80737.fon
del /q /f Windows\Fonts\ega80850.fon
del /q /f Windows\Fonts\ega80852.fon
del /q /f Windows\Fonts\ega80857.fon
del /q /f Windows\Fonts\ega80866.fon
del /q /f Windows\Fonts\ega80869.fon
del /q /f Windows\Fonts\ega80woa.fon
del /q /f Windows\Fonts\h8514fix.fon
del /q /f Windows\Fonts\h8514oem.fon
del /q /f Windows\Fonts\h8514sys.fon
del /q /f Windows\Fonts\hvgafix.fon
del /q /f Windows\Fonts\hvgasys.fon
del /q /f Windows\Fonts\j8514fix.fon
del /q /f Windows\Fonts\j8514oem.fon
del /q /f Windows\Fonts\j8514sys.fon
del /q /f Windows\Fonts\jvgafix.fon
del /q /f Windows\Fonts\jvgasys.fon
del /q /f Windows\Fonts\s8514fix.fon
del /q /f Windows\Fonts\s8514oem.fon
del /q /f Windows\Fonts\s8514sys.fon
del /q /f Windows\Fonts\svgafix.fon
del /q /f Windows\Fonts\svgasys.fon
rd /s /q Windows\inf\de-DE
rd /s /q Windows\inf\PERFLIB
rd /s /q Windows\inf\RemoteAccess
del /q /f Windows\inf\netavpna.inf
del /q /f Windows\inf\netavpnt.inf
del /q /f Windows\inf\netip6.inf
del /q /f Windows\inf\netloop.inf
del /q /f Windows\inf\netmscli.inf
del /q /f Windows\inf\netnb.inf
del /q /f Windows\inf\netrasa.inf
del /q /f Windows\inf\netrast.inf
del /q /f Windows\inf\netsstpa.inf
del /q /f Windows\inf\netsstpt.inf
del /q /f Windows\inf\nettcpip.inf
del /q /f Windows\inf\nettun.inf
del /q /f Windows\inf\sbp2.inf
del /q /f Windows\inf\wstorflt.inf
del /q /f Windows\inf\wvmbus.inf
del /q /f Windows\inf\wvmbushid.inf
del /q /f Windows\inf\wvmic.inf
rd /s /q Windows\servicing\SQM
del /q /f Windows\servicing\Sessions\*.back.xml
del /q /f Windows\servicing\Version\6.1.7601.17514\x86_installed

del /q /f sources\alert.gif
del /q /f sources\appcompat.xsl
del /q /f sources\appcompat_bidi.xsl
del /q /f sources\appcompat_detailed_bidi_txt.xsl
del /q /f sources\appcompat_detailed_txt.xsl
del /q /f sources\compatprovider.dll
del /q /f sources\diager.dll
del /q /f sources\diagnostic.dll
del /q /f sources\dismcore.dll
del /q /f sources\dismcoreps.dll
del /q /f sources\dismhost.exe
del /q /f sources\dismprov.dll
del /q /f sources\folderprovider.dll
del /q /f sources\hwexclude.txt
del /q /f sources\idwbinfo.txt
del /q /f sources\input.dll
del /q /f sources\locale.nls
del /q /f sources\logprovider.dll
del /q /f sources\ndiscompl.dll
del /q /f sources\nlsbres.dll
del /q /f sources\ntdsupg.dll
del /q /f sources\pnpibs.dll
del /q /f sources\sdbapiu.dll
del /q /f sources\sqmapi.dll
del /q /f sources\ssshim.dll
del /q /f sources\testplugin.dll
del /q /f sources\upgloader.dll
del /q /f sources\upgreport.dll
del /q /f sources\uxlibres.dll
del /q /f sources\warning.gif
del /q /f sources\xmllite.dll
del /q /f Windows\bfsvc.exe
del /q /f Windows\regedit.exe
del /q /f Windows\Boot\DVD\PCAT\BCD
del /q /f Windows\Boot\DVD\PCAT\boot.sdi
del /q /f "Windows\Boot\DVD\PCAT\etfsboot.com"
del /q /f Windows\Boot\DVD\PCAT\de-DE\bootfix.bin
del /q /f Windows\Boot\EFI\bootmgfw.efi
del /q /f Windows\Boot\EFI\bootmgr.efi
del /q /f Windows\Boot\EFI\memtest.efi
del /q /f Windows\Boot\EFI\de-DE\bootmgfw.efi.mui
del /q /f Windows\Boot\EFI\de-DE\bootmgr.efi.mui
del /q /f Windows\Boot\EFI\de-DE\memtest.efi.mui
del /q /f Windows\Boot\Fonts\wgl4_boot.ttf
del /q /f Windows\Fonts\fms_metadata.xml
del /q /f Windows\Fonts\vga737.fon
del /q /f Windows\Fonts\vga775.fon
del /q /f Windows\Fonts\vga850.fon
del /q /f Windows\Fonts\vga852.fon
del /q /f Windows\Fonts\vga855.fon
del /q /f Windows\Fonts\vga857.fon
del /q /f Windows\Fonts\vga860.fon
del /q /f Windows\Fonts\vga861.fon
del /q /f Windows\Fonts\vga863.fon
del /q /f Windows\Fonts\vga865.fon
del /q /f Windows\Fonts\vga866.fon
del /q /f Windows\Fonts\vga869.fon
del /q /f Windows\Fonts\vga932.fon
del /q /f Windows\Fonts\vga936.fon
del /q /f Windows\Fonts\vga949.fon
del /q /f Windows\Fonts\vga950.fon
del /q /f Windows\Fonts\vgaf1255.fon
del /q /f Windows\Fonts\vgaf1256.fon
del /q /f Windows\Fonts\vgaf1257.fon
del /q /f Windows\Fonts\vgaf874.fon
del /q /f Windows\Fonts\vgafix.fon
del /q /f Windows\Fonts\vgafixe.fon
del /q /f Windows\Fonts\vgafixg.fon
del /q /f Windows\Fonts\vgafixr.fon
del /q /f Windows\Fonts\vgafixt.fon
del /q /f Windows\Fonts\vgas1255.fon
del /q /f Windows\Fonts\vgas1256.fon
del /q /f Windows\Fonts\vgas1257.fon
del /q /f Windows\Fonts\vgas874.fon
del /q /f Windows\Fonts\vgasys.fon
del /q /f Windows\Fonts\vgasyse.fon
del /q /f Windows\Fonts\vgasysg.fon
del /q /f Windows\Fonts\vgasysr.fon
del /q /f Windows\Fonts\vgasyst.fon
del /q /f Windows\inf\ipmidrv.inf
del /q /f Windows\inf\msports.inf
del /q /f Windows\inf\mtconfig.inf
del /q /f Windows\inf\tpm.inf
del /q /f Windows\inf\vhdmp.inf
del /q /f Windows\inf\wd.inf
del /q /f Windows\inf\wstorvsc.inf
del /q /f Windows\servicing\CbsMsg.dll
del /q /f Windows\servicing\TrustedInstaller.exe
del /q /f Windows\servicing\wrpintapi.dll
del /q /f Windows\servicing\GC64\tzupd.exe
del /q /f Windows\servicing\Packages\Microsoft-Hyper-V-WinPE-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Hyper-V-WinPE-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Client-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Client-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Client-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Client-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Common-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Common-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Common-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Common-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Server-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Server-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Server-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Server-Wired-Network-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Winpe-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Winpe-Drivers-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-Winpe-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-Winpe-Drivers-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-WinPE-LanguagePack-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-WinPE-LanguagePack-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\Microsoft-Windows-WinPE-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\Microsoft-Windows-WinPE-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Scripting-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Scripting-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Scripting-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Scripting-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Setup-Client-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Setup-Client-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Setup-Client-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Setup-Client-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Setup-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Setup-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-Setup-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-Setup-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-SRT-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-SRT-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-SRT-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-SRT-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-WDS-Tools-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-WDS-Tools-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-WDS-Tools-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-WDS-Tools-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-WMI-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-WMI-Package~31bf3856ad364e35~amd64~~6.1.7601.17514.mum
del /q /f Windows\servicing\Packages\WinPE-WMI-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.cat
del /q /f Windows\servicing\Packages\WinPE-WMI-Package~31bf3856ad364e35~amd64~de-DE~6.1.7601.17514.mum
del /q /f Windows\servicing\Sessions\10348_384119140.xml
del /q /f Windows\servicing\Sessions\11592_384057441.xml
del /q /f Windows\servicing\Sessions\11952_383190310.xml
del /q /f Windows\servicing\Sessions\12420_385443448.xml
del /q /f Windows\servicing\Sessions\23608_384092604.xml
del /q /f Windows\servicing\Sessions\26432_384099140.xml
del /q /f Windows\servicing\Sessions\26460_384070935.xml
del /q /f Windows\servicing\Sessions\30504_385458471.xml
del /q /f Windows\servicing\Sessions\34716_384038409.xml
del /q /f Windows\servicing\Sessions\37660_384079640.xml
del /q /f Windows\servicing\Sessions\38428_385469750.xml
del /q /f Windows\servicing\Sessions\41416_384086738.xml
del /q /f Windows\servicing\Sessions\6336_385415680.xml
del /q /f Windows\servicing\Sessions\7900_383009115.xml
del /q /f Windows\servicing\Sessions\Sessions.xml
del /q /f Windows\servicing\Version\6.1.7601.17514\amd64_installed
del /q /f Windows\System32\advpack.dll
del /q /f Windows\System32\api-ms-win-core-console-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-datetime-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-debug-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-delayload-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-errorhandling-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-fibers-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-file-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-handle-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-heap-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-interlocked-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-io-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-libraryloader-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-localization-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-localregistry-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-memory-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-misc-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-namedpipe-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-processenvironment-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-processthreads-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-profile-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-rtlsupport-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-string-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-synch-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-sysinfo-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-threadpool-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-util-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-core-xstate-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-security-base-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-security-lsalookup-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-security-sddl-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-service-core-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-service-management-l1-1-0.dll
del /q /f Windows\System32\api-ms-win-service-management-l2-1-0.dll
del /q /f Windows\System32\api-ms-win-service-winsvc-l1-1-0.dll
del /q /f Windows\System32\apircl.dll
del /q /f Windows\System32\apss.dll
del /q /f Windows\System32\asycfilt.dll
del /q /f Windows\System32\atmfd.dll
del /q /f Windows\System32\atmlib.dll
del /q /f Windows\System32\attrib.exe
del /q /f Windows\System32\batt.dll
del /q /f Windows\System32\BOOTVID.DLL
del /q /f Windows\System32\browcli.dll
del /q /f Windows\System32\browseui.dll
del /q /f Windows\System32\C_IS2022.DLL
del /q /f Windows\System32\cabinet.dll
del /q /f Windows\System32\certcli.dll
del /q /f Windows\System32\chcp.com
del /q /f Windows\System32\chkdsk.exe
del /q /f Windows\System32\clb.dll
del /q /f Windows\System32\cmd.exe
del /q /f Windows\System32\cmipnpinstall.dll
del /q /f Windows\System32\cryptdlg.dll
del /q /f Windows\System32\cryptxml.dll
del /q /f Windows\System32\cscript.exe
del /q /f Windows\System32\davhlpr.dll
del /q /f Windows\System32\dciman32.dll
del /q /f Windows\System32\dfscli.dll
del /q /f Windows\System32\dinotify.exe
del /q /f Windows\System32\Dism.exe
del /q /f Windows\System32\dispex.dll
del /q /f Windows\System32\dllhost.exe
del /q /f Windows\System32\dllhst3g.exe
del /q /f Windows\System32\dmrc.dll
del /q /f Windows\System32\doskey.exe
del /q /f Windows\System32\dpapimig.exe
del /q /f Windows\System32\dpx.dll
del /q /f Windows\System32\dsrole.dll
del /q /f Windows\System32\duser.dll
del /q /f Windows\System32\dwmapi.dll
del /q /f Windows\System32\efscore.dll
del /q /f Windows\System32\efssvc.dll
del /q /f Windows\System32\efsutil.dll
del /q /f Windows\System32\expand.exe
del /q /f Windows\System32\feclient.dll
del /q /f Windows\System32\find.exe
del /q /f Windows\System32\fixmapi.exe
del /q /f Windows\System32\fltMC.exe
del /q /f Windows\System32\fms.dll
del /q /f Windows\System32\fontsub.dll
del /q /f "Windows\System32\format.com"
del /q /f Windows\System32\framedyn.dll
del /q /f Windows\System32\framedynos.dll
del /q /f Windows\System32\gacinstall.dll
del /q /f Windows\System32\hid.dll
del /q /f Windows\System32\hidserv.dll
del /q /f Windows\System32\icacls.exe
del /q /f Windows\System32\idndl.dll
del /q /f Windows\System32\imageres.dll
del /q /f Windows\System32\kmddsp.tsp
del /q /f Windows\System32\ktmw32.dll
del /q /f Windows\System32\linkinfo.dll
del /q /f Windows\System32\lmhsvc.dll
del /q /f Windows\System32\luainstall.dll
del /q /f Windows\System32\lz32.dll
del /q /f Windows\System32\mapi32.dll
del /q /f Windows\System32\mapistub.dll
del /q /f Windows\System32\mcbuilder.exe
del /q /f Windows\System32\mcupdate_GenuineIntel.dll
del /q /f Windows\System32\mf3216.dll
del /q /f Windows\System32\microsoft-windows-hal-events.dll
del /q /f Windows\System32\microsoft-windows-kernel-power-events.dll
del /q /f Windows\System32\microsoft-windows-kernel-processor-power-events.dll
del /q /f "Windows\System32\mode.com"
del /q /f "Windows\System32\more.com"
del /q /f Windows\System32\mprapi.dll
del /q /f Windows\System32\mprmsg.dll
del /q /f Windows\System32\MRINFO.EXE
del /q /f Windows\System32\msafd.dll
del /q /f Windows\System32\msdelta.dll
del /q /f Windows\System32\msiltcfg.dll
del /q /f Windows\System32\msls31.dll
del /q /f Windows\System32\mspatcha.dll
del /q /f Windows\System32\msports.dll
del /q /f Windows\System32\msvcirt.dll
del /q /f Windows\System32\mswsock.dll
del /q /f Windows\System32\mtxdm.dll
del /q /f Windows\System32\nci.dll
del /q /f Windows\System32\ncobjapi.dll
del /q /f Windows\System32\ndptsp.tsp
del /q /f Windows\System32\netcfg.exe
del /q /f Windows\System32\Nlsdl.dll
del /q /f Windows\System32\normaliz.dll
del /q /f Windows\System32\normidna.nls
del /q /f Windows\System32\normnfc.nls
del /q /f Windows\System32\normnfd.nls
del /q /f Windows\System32\normnfkc.nls
del /q /f Windows\System32\normnfkd.nls
del /q /f Windows\System32\oleacc.dll
del /q /f Windows\System32\oleacchooks.dll
del /q /f Windows\System32\oleaccrc.dll
del /q /f Windows\System32\oleres.dll
del /q /f Windows\System32\onlinedeploy.cmd
del /q /f Windows\System32\pcwum.dll
del /q /f Windows\System32\perfdisk.dll
del /q /f Windows\System32\perfnet.dll
del /q /f Windows\System32\perfos.dll
del /q /f Windows\System32\perfproc.dll
del /q /f Windows\System32\pnpsetup.dll
del /q /f Windows\System32\pnpui.dll
del /q /f Windows\System32\poqexec.exe
del /q /f Windows\System32\powrprof.dll
del /q /f Windows\System32\prflbmsg.dll
del /q /f Windows\System32\procinst.dll
del /q /f Windows\System32\propsys.dll
del /q /f Windows\System32\provthrd.dll
del /q /f Windows\System32\QUTIL.DLL
del /q /f Windows\System32\reg.exe
del /q /f Windows\System32\regapi.dll
del /q /f Windows\System32\regedt32.exe
del /q /f Windows\System32\regsvr32.exe
del /q /f Windows\System32\replace.exe
del /q /f Windows\System32\resutils.dll
del /q /f Windows\System32\riched32.dll
del /q /f Windows\System32\rnr20.dll
del /q /f Windows\System32\sacsess.exe
del /q /f Windows\System32\sacsvr.dll
del /q /f Windows\System32\scecli.dll
del /q /f Windows\System32\scesrv.dll
del /q /f Windows\System32\scext.dll
del /q /f Windows\System32\schedcli.dll
del /q /f Windows\System32\schema.dat
del /q /f Windows\System32\scrobj.dll
del /q /f Windows\System32\scrrun.dll
del /q /f Windows\System32\sdhcinst.dll
del /q /f Windows\System32\SensApi.dll
del /q /f Windows\System32\sfc.dll
del /q /f Windows\System32\sfc_os.dll
del /q /f Windows\System32\slc.dll
del /q /f Windows\System32\snmpapi.dll
del /q /f Windows\System32\softpub.dll
del /q /f Windows\System32\SSShim.dll
del /q /f Windows\System32\startnet.cmd
del /q /f Windows\System32\stdole2.tlb
del /q /f Windows\System32\stdole32.tlb
del /q /f Windows\System32\streamci.dll
del /q /f Windows\System32\subst.exe
del /q /f Windows\System32\sxshared.dll
del /q /f Windows\System32\sxstrace.exe
del /q /f Windows\System32\tbssvc.dll
del /q /f "Windows\System32\tree.com"
del /q /f Windows\System32\tzres.dll
del /q /f Windows\System32\ubpm.dll
del /q /f Windows\System32\UIAutomationCore.dll
del /q /f Windows\System32\umpo.dll
del /q /f Windows\System32\ureg.dll
del /q /f Windows\System32\UXInit.dll
del /q /f Windows\System32\vga.dll
del /q /f Windows\System32\w32topl.dll
del /q /f Windows\System32\wbemcomn.dll
del /q /f Windows\System32\wevtutil.exe
del /q /f Windows\System32\wimgapi.dll
del /q /f Windows\System32\winbrand.dll
del /q /f Windows\System32\winsockhc.dll
del /q /f Windows\System32\wmi.dll
del /q /f Windows\System32\WmiMgmt.msc
del /q /f Windows\System32\wmiprop.dll
del /q /f Windows\System32\wowreg32.exe
del /q /f Windows\System32\ws2help.dll
del /q /f Windows\System32\wscript.exe
del /q /f Windows\System32\wshcon.dll
del /q /f Windows\System32\wshelper.dll
del /q /f Windows\System32\wship6.dll
del /q /f Windows\System32\wshom.ocx
del /q /f Windows\System32\WSHTCPIP.DLL
del /q /f Windows\System32\wsock32.dll
del /q /f Windows\System32\xmllite.dll
del /q /f Windows\System32\Dism\CbsProvider.dll
del /q /f Windows\System32\Dism\CompatProvider.dll
del /q /f Windows\System32\Dism\DismHost.exe
del /q /f Windows\System32\Dism\DmiProvider.dll
del /q /f Windows\System32\Dism\IntlProvider.dll
del /q /f Windows\System32\Dism\OSProvider.dll
del /q /f Windows\System32\Dism\PEProvider.dll
del /q /f Windows\System32\Dism\SmiProvider.dll
del /q /f Windows\System32\Dism\UnattendProvider.dll
del /q /f Windows\System32\Dism\WimProvider.dll
del /q /f Windows\System32\drivers\afd.sys
del /q /f Windows\System32\drivers\agilevpn.sys
del /q /f Windows\System32\drivers\amdppm.sys
del /q /f Windows\System32\drivers\asyncmac.sys
del /q /f Windows\System32\drivers\bowser.sys
del /q /f Windows\System32\drivers\cdfs.sys
del /q /f Windows\System32\drivers\CmBatt.sys
del /q /f Windows\System32\drivers\dfsc.sys
del /q /f Windows\System32\drivers\dumpfve.sys
del /q /f Windows\System32\drivers\dxg.sys
del /q /f Windows\System32\drivers\fileinfo.sys
del /q /f Windows\System32\drivers\filetrace.sys
del /q /f Windows\System32\drivers\fsdepends.sys
del /q /f Windows\System32\drivers\FWPKCLNT.SYS
del /q /f Windows\System32\drivers\hidbatt.sys
del /q /f Windows\System32\drivers\IPMIDrv.sys
del /q /f Windows\System32\drivers\ks.sys
del /q /f Windows\System32\drivers\ksthunk.sys
del /q /f Windows\System32\drivers\mcd.sys
del /q /f Windows\System32\drivers\mpsdrv.sys
del /q /f Windows\System32\drivers\mrxsmb.sys
del /q /f Windows\System32\drivers\mrxsmb10.sys
del /q /f Windows\System32\drivers\mrxsmb20.sys
del /q /f Windows\System32\drivers\MsftWdf_Kernel_01009_Inbox_Critical.Wdf
del /q /f Windows\System32\drivers\mskssrv.sys
del /q /f Windows\System32\drivers\mspclock.sys
del /q /f Windows\System32\drivers\mspqm.sys
del /q /f Windows\System32\drivers\mssmbios.sys
del /q /f Windows\System32\drivers\mstee.sys
del /q /f Windows\System32\drivers\MTConfig.sys
del /q /f Windows\System32\drivers\mup.sys
del /q /f Windows\System32\drivers\ndistapi.sys
del /q /f Windows\System32\drivers\ndiswan.sys
del /q /f Windows\System32\drivers\ndproxy.sys
del /q /f Windows\System32\drivers\netbt.sys
del /q /f Windows\System32\drivers\nsiproxy.sys
del /q /f Windows\System32\drivers\null.sys
del /q /f Windows\System32\drivers\parport.sys
del /q /f Windows\System32\drivers\pcw.sys
del /q /f Windows\System32\drivers\rdbss.sys
del /q /f Windows\System32\drivers\sacdrv.sys
del /q /f Windows\System32\drivers\serenum.sys
del /q /f Windows\System32\drivers\serial.sys
del /q /f Windows\System32\drivers\sermouse.sys
del /q /f Windows\System32\drivers\smb.sys
del /q /f Windows\System32\drivers\storvsc.sys
del /q /f Windows\System32\drivers\stream.sys
del /q /f Windows\System32\drivers\swenum.sys
del /q /f Windows\System32\drivers\tcpip.sys
del /q /f Windows\System32\drivers\tdi.sys
del /q /f Windows\System32\drivers\tdx.sys
del /q /f Windows\System32\drivers\termdd.sys
del /q /f Windows\System32\drivers\vhdmp.sys
del /q /f Windows\System32\drivers\wanarp.sys
del /q /f Windows\System32\drivers\wd.sys
del /q /f Windows\System32\drivers\wimmount.sys
del /q /f Windows\System32\drivers\wmiacpi.sys
del /q /f Windows\System32\drivers\ws2ifsl.sys
del /q /f Windows\System32\drivers\de-DE\afd.sys.mui
del /q /f Windows\System32\drivers\de-DE\amdppm.sys.mui
del /q /f Windows\System32\drivers\de-DE\IPMIDrv.sys.mui
del /q /f Windows\System32\drivers\de-DE\mssmbios.sys.mui
del /q /f Windows\System32\drivers\de-DE\MTConfig.sys.mui
del /q /f Windows\System32\drivers\de-DE\parport.sys.mui
del /q /f Windows\System32\drivers\de-DE\rdbss.sys.mui
del /q /f Windows\System32\drivers\de-DE\sacdrv.sys.mui
del /q /f Windows\System32\drivers\de-DE\serial.sys.mui
del /q /f Windows\System32\drivers\de-DE\sermouse.sys.mui
del /q /f Windows\System32\drivers\de-DE\tcpip.sys.mui
del /q /f Windows\System32\drivers\de-DE\vhdmp.sys.mui
del /q /f Windows\System32\drivers\de-DE\wd.sys.mui
del /q /f Windows\System32\drivers\de-DE\ws2ifsl.sys.mui
del /q /f Windows\System32\DriverStore\de-DE\ipmidrv.inf_loc
del /q /f Windows\System32\DriverStore\de-DE\MTConfig.inf_loc
del /q /f Windows\System32\DriverStore\de-DE\tpm.inf_loc
del /q /f Windows\System32\DriverStore\de-DE\vhdmp.inf_loc
del /q /f Windows\System32\DriverStore\de-DE\wd.inf_loc
del /q /f Windows\System32\setup\tssysprep.dll
del /q /f Windows\winsxs\Manifests\amd64_microsoft.windows.c..-controls.resources_6595b64144ccf1df_5.82.7601.17514_en-us_bae1f2089dbb5296.manifest
del /q /f Windows\winsxs\Manifests\amd64_microsoft.windows.c..-controls.resources_6595b64144ccf1df_6.0.7601.17514_en-us_1044a96c4400fb99.manifest
del /q /f Windows\winsxs\Manifests\x86_microsoft-windows-servicingstack_31bf3856ad364e35_6.1.7601.17514_none_0b66cb34258c936f.manifest
del /q /f Windows\System32\bootres.dll
del /q /f Windows\System32\imagesp1.dll

rd /s /q Windows\System32\catroot
rd /s /q Windows\System32\AdvancedInstallers
rd /s /q Windows\System32\catroot2
rd /s /q Windows\System32\CodeIntegrity
rd /s /q Windows\System32\en-US
rd /s /q Windows\System32\GroupPolicy
rd /s /q Windows\System32\GroupPolicyUsers
rd /s /q Windows\System32\LogFiles
rd /s /q Windows\System32\migration
rd /s /q Windows\System32\MUI
rd /s /q Windows\System32\NetworkList
rd /s /q Windows\System32\ras
rd /s /q Windows\System32\Recovery
rd /s /q Windows\System32\restore
rd /s /q Windows\System32\SMI
rd /s /q Windows\System32\spp
rd /s /q Windows\System32\sysprep
rd /s /q Windows\System32\wbem
rd /s /q Windows\System32\wdi
rd /s /q Windows\System32\wfp
rd /s /q Windows\System32\WinBioDatabase
rd /s /q Windows\System32\WinBioPlugIns
rd /s /q Windows\System32\winevt
rd /s /q Windows\System32\oobe\de-DE
rd /s /q Windows\System32\config\TxR
rd /s /q Windows\System32\config\RegBack
rd /s /q Windows\System32\config\Journal
rd /s /q Windows\System32\config\systemprofile\AppData
del /q /f Windows\System32\config\BCD-Template
del /q /f Windows\System32\DriverStore\infcache.1
del /q /f Windows\System32\activeds.dll
del /q /f Windows\System32\activeds.tlb
del /q /f Windows\System32\adsldpc.dll
del /q /f Windows\System32\apds.dll
del /q /f Windows\System32\ARP.EXE
del /q /f Windows\System32\authui.dll
del /q /f Windows\System32\authz.dll
del /q /f Windows\System32\autochk.exe
del /q /f Windows\System32\autoconv.exe
del /q /f Windows\System32\AuxiliaryDisplayClassInstaller.dll
del /q /f Windows\System32\bderepair.dll
del /q /f Windows\System32\bdeui.dll
del /q /f Windows\System32\BdeUnlockWizard.exe
del /q /f Windows\System32\BitLockerWizard.exe
del /q /f Windows\System32\BitLockerWizardElev.exe
del /q /f Windows\System32\bmrui.exe
del /q /f Windows\System32\BootRec.exe
del /q /f Windows\System32\bthci.dll
del /q /f Windows\System32\printui.dll
del /q /f Windows\System32\bthserv.dll
del /q /f Windows\System32\C_G18030.DLL
del /q /f Windows\System32\clusapi.dll
del /q /f Windows\System32\cmifw.dll
del /q /f Windows\System32\comres.dll
del /q /f Windows\System32\cryptui.dll
del /q /f Windows\System32\dbgeng.dll
del /q /f Windows\System32\dbghelp.dll
del /q /f Windows\System32\defragproxy.dll
del /q /f Windows\System32\defragsvc.dll
del /q /f Windows\System32\dhcpcmonitor.dll
del /q /f Windows\System32\dhcpcore.dll
del /q /f Windows\System32\dhcpcore6.dll
del /q /f Windows\System32\dhcpcsvc.dll
del /q /f Windows\System32\dhcpcsvc6.dll
del /q /f Windows\System32\DHCPQEC.DLL
del /q /f Windows\System32\dnscacheugc.exe
del /q /f Windows\System32\dnsrslvr.dll
del /q /f Windows\System32\dskquota.dll
del /q /f Windows\System32\dui70.dll
del /q /f Windows\System32\dwmcore.dll
del /q /f Windows\System32\Eap3Host.exe
del /q /f Windows\System32\eapp3hst.dll
del /q /f Windows\System32\eappcfg.dll
del /q /f Windows\System32\eappgnui.dll
del /q /f Windows\System32\eapphost.dll
del /q /f Windows\System32\eappprxy.dll
del /q /f Windows\System32\EAPQEC.DLL
del /q /f Windows\System32\eapsvc.dll
del /q /f Windows\System32\esent.dll
del /q /f Windows\System32\esentutl.exe
del /q /f Windows\System32\eventcls.dll
del /q /f Windows\System32\f3ahvoas.dll
del /q /f Windows\System32\finger.exe
del /q /f Windows\System32\FirewallAPI.dll
del /q /f Windows\System32\ftp.exe
del /q /f Windows\System32\fveapi.dll
del /q /f Windows\System32\fveapibase.dll
del /q /f Windows\System32\fvecerts.dll
del /q /f Windows\System32\fvecpl.dll
del /q /f Windows\System32\fveRecover.dll
del /q /f Windows\System32\fveui.dll
del /q /f Windows\System32\fvewiz.dll
del /q /f Windows\System32\FWPUCLNT.DLL
del /q /f Windows\System32\FwRemoteSvr.dll
del /q /f Windows\System32\hhsetup.dll
del /q /f Windows\System32\httpapi.dll
del /q /f Windows\System32\IcCoinstall.dll
del /q /f Windows\System32\icfupgd.dll
del /q /f Windows\System32\IKEEXT.DLL
del /q /f Windows\System32\imapi.dll
del /q /f Windows\System32\imapi2.dll
del /q /f Windows\System32\imapi2fs.dll
del /q /f Windows\System32\inetmib1.dll
del /q /f Windows\System32\ipconfig.exe
del /q /f Windows\System32\IPSECSVC.DLL
del /q /f Windows\System32\iscsilog.dll
del /q /f Windows\System32\jscript.dll
del /q /f Windows\System32\jsproxy.dll
del /q /f Windows\System32\kerberos.dll
del /q /f Windows\System32\keyiso.dll
del /q /f Windows\System32\loadperf.dll
del /q /f Windows\System32\lodctr.exe
del /q /f Windows\System32\manage-bde.exe
del /q /f Windows\System32\manage-bde.wsf
del /q /f Windows\System32\MdSched.exe
del /q /f Windows\System32\mfc42.dll
del /q /f Windows\System32\mfc42u.dll
del /q /f Windows\System32\MPSSVC.dll
del /q /f Windows\System32\msvcp60.dll
del /q /f Windows\System32\msxml3.dll
del /q /f Windows\System32\msxml6.dll
del /q /f Windows\System32\nbtstat.exe
del /q /f Windows\System32\ncsi.dll
del /q /f Windows\System32\net.exe
del /q /f Windows\System32\net1.exe
del /q /f Windows\System32\netbtugc.exe
del /q /f Windows\System32\netcfgx.dll
del /q /f Windows\System32\netiohlp.dll
del /q /f Windows\System32\netiougc.exe
del /q /f Windows\System32\netlogon.dll
del /q /f Windows\System32\netman.dll
del /q /f Windows\System32\netsh.exe
del /q /f Windows\System32\netshell.dll
del /q /f Windows\System32\NETSTAT.EXE
del /q /f Windows\System32\nlaapi.dll
del /q /f Windows\System32\nlasvc.dll
del /q /f Windows\System32\notepad.exe
del /q /f Windows\System32\nrpsrv.dll
del /q /f Windows\System32\nshwfp.dll
del /q /f Windows\System32\ntlanman.dll
del /q /f Windows\System32\ntprint.dll
del /q /f Windows\System32\ntprint.exe
del /q /f Windows\System32\ntshrui.dll
del /q /f Windows\System32\odbc32.dll
del /q /f Windows\System32\odbccp32.dll
del /q /f Windows\System32\odbcint.dll
del /q /f Windows\System32\odbctrac.dll
del /q /f Windows\System32\PATHPING.EXE
del /q /f Windows\System32\perfc009.dat
del /q /f Windows\System32\perfc007.dat
del /q /f Windows\System32\perfd007.dat
del /q /f Windows\System32\perfh007.dat
del /q /f Windows\System32\perfi007.dat
del /q /f Windows\System32\perfctrs.dll
del /q /f Windows\System32\perfd009.dat
del /q /f Windows\System32\perfh009.dat
del /q /f Windows\System32\perfi009.dat
del /q /f Windows\System32\PING.EXE
del /q /f Windows\System32\PkgMgr.exe
del /q /f Windows\System32\pnidui.dll
del /q /f Windows\System32\polstore.dll
del /q /f Windows\System32\print.exe
del /q /f Windows\System32\rasadhlp.dll
del /q /f Windows\System32\rasapi32.dll
del /q /f Windows\System32\rasauto.dll
del /q /f Windows\System32\rasautou.exe
del /q /f Windows\System32\rascfg.dll
del /q /f Windows\System32\raschap.dll
del /q /f Windows\System32\rasctrnm.h
del /q /f Windows\System32\rasctrs.dll
del /q /f Windows\System32\rasdiag.dll
del /q /f Windows\System32\rasdlg.dll
del /q /f Windows\System32\rasman.dll
del /q /f Windows\System32\rasmans.dll
del /q /f Windows\System32\rasmbmgr.dll
del /q /f Windows\System32\rasmontr.dll
del /q /f Windows\System32\rasmxs.dll
del /q /f Windows\System32\rasppp.dll
del /q /f Windows\System32\rasser.dll
del /q /f Windows\System32\rastapi.dll
del /q /f Windows\System32\rastls.dll
del /q /f Windows\System32\ReAgent.dll
del /q /f Windows\System32\recdisc.exe
del /q /f Windows\System32\recover.exe
del /q /f Windows\System32\repair-bde.exe
del /q /f Windows\System32\riched20.dll
del /q /f Windows\System32\Robocopy.exe
del /q /f Windows\System32\ROUTE.EXE
del /q /f Windows\System32\rstrui.exe
del /q /f Windows\System32\schannel.dll
del /q /f Windows\System32\SmiEngine.dll
del /q /f Windows\System32\spp.dll
del /q /f Windows\System32\srclient.dll
del /q /f Windows\System32\srcore.dll
del /q /f Windows\System32\sstpsvc.dll
del /q /f Windows\System32\swprv.dll
del /q /f Windows\System32\takeown.exe
del /q /f Windows\System32\tapi32.dll
del /q /f Windows\System32\taskmgr.exe
del /q /f Windows\System32\tcpipcfg.dll
del /q /f Windows\System32\tcpmib.dll
del /q /f Windows\System32\TCPSVCS.EXE
del /q /f Windows\System32\TRACERT.EXE
del /q /f Windows\System32\unlodctr.exe
del /q /f Windows\System32\vbscript.dll
del /q /f Windows\System32\VmbusCoinstaller.dll
del /q /f Windows\System32\vmbusres.dll
del /q /f Windows\System32\VmdCoinstall.dll
del /q /f Windows\System32\vmicres.dll
del /q /f Windows\System32\vmicsvc.exe
del /q /f Windows\System32\vmictimeprovider.dll
del /q /f Windows\System32\vmstorfltres.dll
del /q /f Windows\System32\vpnike.dll
del /q /f Windows\System32\vpnikeapi.dll
del /q /f Windows\System32\vss_ps.dll
del /q /f Windows\System32\vssapi.dll
del /q /f Windows\System32\vsstrace.dll
del /q /f Windows\System32\VSSVC.exe
del /q /f Windows\System32\w32time.dll
del /q /f Windows\System32\wbiosrvc.dll
del /q /f Windows\System32\wdigest.dll
del /q /f Windows\System32\wdscapture.exe
del /q /f Windows\System32\wdscapture.inf
del /q /f Windows\System32\wdscore.dll
del /q /f Windows\System32\wdscsl.dll
del /q /f Windows\System32\WdsImage.dll
del /q /f Windows\System32\wdstptc.dll
del /q /f Windows\System32\webio.dll
del /q /f Windows\System32\webservices.dll
del /q /f Windows\System32\wer.dll
del /q /f Windows\System32\werdiagcontroller.dll
del /q /f Windows\System32\wermgr.exe
del /q /f Windows\System32\werui.dll
del /q /f Windows\System32\wevtsvc.dll
del /q /f Windows\System32\wfapigp.dll
del /q /f Windows\System32\wimserv.exe
del /q /f Windows\System32\winbio.dll
del /q /f Windows\System32\WindowsCodecs.dll
del /q /f Windows\System32\winhttp.dll
del /q /f Windows\System32\winmm.dll
del /q /f Windows\System32\winpe.bmp
del /q /f Windows\System32\WinSCard.dll
del /q /f Windows\System32\winspool.drv
del /q /f Windows\System32\wlaninst.dll
del /q /f Windows\System32\wlanutil.dll
del /q /f Windows\System32\wmicmiplugin.dll
del /q /f Windows\System32\wshnetbs.dll
rd /s /q Windows\System32\drivers\UMDF\
del /q /f Windows\System32\drivers\1394bus.sys
del /q /f Windows\System32\drivers\1394ohci.sys
del /q /f Windows\System32\drivers\bxvbda.sys
del /q /f Windows\System32\drivers\evbda.sys
del /q /f Windows\System32\drivers\fdc.sys
del /q /f Windows\System32\drivers\flpydisk.sys
del /q /f Windows\System32\drivers\hdaudbus.sys
del /q /f Windows\System32\drivers\pcmcia.sys
del /q /f Windows\System32\drivers\raspptp.sys
del /q /f Windows\System32\drivers\sbp2port.sys
del /q /f Windows\System32\drivers\vmbus.sys
del /q /f Windows\System32\drivers\VMBusHID.sys
del /q /f Windows\System32\drivers\vmstorfl.sys
del /q /f Windows\System32\drivers\wacompen.sys
del /q /f Windows\System32\drivers\winhv.sys
rd /s /q Windows\System32\DriverStore\FileRepository\netloop.inf_amd64_neutral_09411f7df59617e8
rd /s /q Windows\System32\DriverStore\FileRepository\nettun.inf_amd64_neutral_01fa6583f9401f6f
rd /s /q Windows\System32\DriverStore\FileRepository\sbp2.inf_amd64_neutral_332943647e950ada
rd /s /q Windows\System32\DriverStore\FileRepository\wnetvsc.inf_amd64_neutral_548addf09cb466fa
rd /s /q Windows\System32\DriverStore\FileRepository\wstorflt.inf_amd64_neutral_3db956c41708f7f5
rd /s /q Windows\System32\DriverStore\FileRepository\wvmbus.inf_amd64_neutral_fca91999602b0343
rd /s /q Windows\System32\DriverStore\FileRepository\wvmbushid.inf_amd64_neutral_6708ad28050a6765
rd /s /q Windows\System32\DriverStore\FileRepository\wvmic.inf_amd64_neutral_b94eb92e8150fa35